services:

  db:
    restart: unless-stopped
    networks:
      - app-network
    image: postgres:13.3-alpine
    volumes:
      - gophermart_pgdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
  
  minio:
    restart: unless-stopped
    networks:
      - app-network
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    volumes:
      - gophermart_minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_USE_SSL=$MINIO_USE_SSL}
      - MINIO_DEFAULT_BUCKETS=${MINIO_DEFAULT_BUCKETS}

networks:
  app-network:
    driver: bridge

volumes:
  gophermart_pgdata:
  gophermart_minio:
