// Code generated by "stringer -type=DataTypeEnum -linecomment -output datatype_enum_string.go"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TextType-1]
	_ = x[BinaryType-2]
}

const _DataTypeEnum_name = "unknowntextbinary"

var _DataTypeEnum_index = [...]uint8{0, 7, 11, 17}

func (i DataTypeEnum) String() string {
	if i < 0 || i >= DataTypeEnum(len(_DataTypeEnum_index)-1) {
		return "DataTypeEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataTypeEnum_name[_DataTypeEnum_index[i]:_DataTypeEnum_index[i+1]]
}
