definitions:
  model.AddTextData:
    properties:
      data:
        type: string
      name:
        maxLength: 250
        type: string
    required:
    - data
    - name
    type: object
  model.DataResponse:
    properties:
      createdAt:
        type: string
      data:
        type: string
      id:
        type: integer
      name:
        type: string
      type:
        $ref: '#/definitions/model.DataTypeEnum'
      updatedAt:
        type: string
    type: object
  model.DataTypeEnum:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-comments:
      BinaryType: binary
      TextType: text
      TypeUnknown: unknown
    x-enum-varnames:
    - TypeUnknown
    - TextType
    - BinaryType
  model.Error:
    properties:
      error:
        type: string
    type: object
  model.RegisterUser:
    properties:
      email:
        maxLength: 250
        type: string
      password:
        maxLength: 250
        type: string
    required:
    - email
    - password
    type: object
  model.TokenResponse:
    properties:
      token:
        type: string
    type: object
  model.UserResponse:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  title: Swagger Gophkeeper API
  version: "1.0"
paths:
  /api/data:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            items:
              $ref: '#/definitions/model.DataResponse'
            type: array
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Get all data
      tags:
      - Data
  /api/data/{dataID}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Data ID
        in: path
        name: dataId
        required: true
        type: integer
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.DataResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity (query)
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Delete data
      tags:
      - Data
    get:
      consumes:
      - application/json
      parameters:
      - description: Data ID
        in: path
        name: dataId
        required: true
        type: integer
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.DataResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/model.Error'
        "404":
          description: Data is not found
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity (query)
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Get data by ID
      tags:
      - Data
  /api/data/binary:
    post:
      consumes:
      - multipart/form-data
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.DataResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity (body)
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Add text data
      tags:
      - Data
  /api/data/binary/{dataID}:
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Data ID
        in: path
        name: dataId
        required: true
        type: integer
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.DataResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity (query or body)
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Update binary data
      tags:
      - Data
  /api/data/text:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AddTextData'
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.DataResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity (body)
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Add text data
      tags:
      - Data
  /api/data/text/{dataID}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Data ID
        in: path
        name: dataId
        required: true
        type: integer
      - description: Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.AddTextData'
      - description: Bearer
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.DataResponse'
        "401":
          description: Unauthorized request
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity (query or body)
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Update text data
      tags:
      - Data
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.TokenResponse'
        "401":
          description: Incorrect password
          schema:
            $ref: '#/definitions/model.Error'
        "404":
          description: Email is not found
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Login user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.UserResponse'
        "409":
          description: Email is already used
          schema:
            $ref: '#/definitions/model.Error'
        "422":
          description: Unprocessable entity
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Regiser user
      tags:
      - Auth
swagger: "2.0"
