definitions:
  model.Error:
    properties:
      error:
        type: string
    type: object
  model.RegisterUser:
    properties:
      email:
        maxLength: 250
        type: string
      password:
        maxLength: 130
        type: string
    required:
    - email
    - password
    type: object
  model.Success:
    properties:
      success:
        type: boolean
    type: object
host: localhost:7000
info:
  contact: {}
  title: Swagger SDK Logger Service API
  version: "1.0"
paths:
  /api/user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.RegisterUser'
      produces:
      - application/json
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/model.Success'
        "409":
          description: Email is already used
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Error
          schema:
            $ref: '#/definitions/model.Error'
      summary: Regiser user
      tags:
      - Log
swagger: "2.0"
